implemented true/false functions for isSubmitted
HackRU/sledge pull request #169
Opened 2021-03-28 02:09 UTC by jgarcia19

2021-03-28 02:37 UTC, samuel-ping submitted a review, later dismissed
Line 73: This seems a little out of place, especially since we don't declare any other functions outright with "let." For the sake of consistency, can you remove this let? But other than that, everything looks a-ok to me! (I also want you to push new changes to test the pipeline :p)

2021-03-28 02:43 UTC, jgarcia19 commented
@samuel-ping the only reason i put that let there is because VS code was showing an error at line 73 without it. If it runs fine without that let feel free to remove it!

2021-03-29 15:24 UTC, samuel-ping commented on server/databaseFunctions.test.js
> +let removeAllCollections = async () => {
and delete this let

2021-03-29 15:24 UTC, samuel-ping commented on server/databaseFunctions.test.js
> +  projectID: testTeamID,
delete this

2021-03-29 17:44 UTC, samuel-ping requested changes
lol sorry for so many comments, take a look at my small comments

2021-03-29 17:44 UTC, samuel-ping commented on server/app.js
> +const { update } = require("./models/submissionSchema.model");
whats this?

2021-03-29 17:44 UTC, samuel-ping commented on server/databaseFunctions.test.js
> +    const res = await request.patch(`/api/submissions/${testTeamID}/${testSubmissionId}/setTrue`);
I think it would be clearer if you called the route /submit and /unsubmit

2021-03-31 16:43 UTC, merged