Admin page
HackRU/sledge pull request #229
Opened 2021-07-08 15:04 UTC by Deep310

Changes made: 
- added eslint-disable in sledge and layout.jsx file because otherwise it gave error saying "Do not nest ternary expressions"
- added admin dashboard component under admin route 
- made a new component PastHackathons which is basically a material ui accordion that displays hackathons and phases

2021-07-11 00:00 UTC, samuel-ping requested changes
good stuff, be sure to turn more things into components

2021-07-11 00:00 UTC, samuel-ping commented on client/src/components/Layout.jsx
> +/* eslint-disable */
probably best to get rid of this line since we are disabling the eslint warnings through the .env file

2021-07-11 00:00 UTC, samuel-ping commented on client/src/components/PastHackathons.jsx
> +        </AccordionDetails>
Turn this into a component!

2021-07-12 14:11 UTC, Deep310 commented on client/src/components/PastHackathons.jsx
> +        </AccordionDetails>
Got it, will make the changes!

2021-09-18 15:21 UTC, merged