Issue 30 draft
HackRU/sledge pull request #40
Opened 2020-04-15 03:32 UTC by sahej172002

not sure how to populate the interface

2020-04-16 00:48 UTC, three requested changes

2020-04-16 00:48 UTC, three commented on src/client/Statistics.ts
> +    if (cloned[i].type === 1 && !(cloned[i].active)) {
You should import and use the `ASSIGNMENT_TYPE_RATING` constant in `constants.ts`.

2020-04-16 00:48 UTC, three commented on src/client/Statistics.ts
> +      if ((!subIndices.includes(cloned[i].submissionIndex)) && (!cloned[i].submissionIndex === undefined)) {
If the assignment is of type rating, you can assume submissionIndex is valid

2020-04-16 00:48 UTC, three commented on src/client/Statistics.ts
> +  return avgArray;
You should return an array of objects, for instance `[{id: 1, plainAverage: .5}, {id: 2, plainAverage: 3}]` could be a valid return.

2020-04-16 00:48 UTC, three commented on src/client/Statistics.ts
> +  return avgArray;
You can also remove `judgeWeightedAverage` from the interface. That's lower priority and can be done in a different PR.

2020-04-16 00:48 UTC, three commented on src/client/Statistics.ts
> +        else {
Nitpick: keep both brackets of else on the same line,

```javascript
if (/* ... */) {
	// True case
} else {
	// False Case
}
```

2020-04-16 00:48 UTC, three commented on src/client/Statistics.ts
> +        if (cloned[k].rating === undefined) {
What are you looking for by checking if `rating` is undefined?

2020-04-16 00:48 UTC, three commented on src/client/Statistics.ts
> +  let cloned = [...responseData.assignments];
What are you trying to do by cloning `assignments`? If you're trying to make a copy to modify things you need to make a deep copy, but I'm not sure how making a copy helps you.

2020-04-16 00:50 UTC, three commented
@sahej172002 I added some comments.

You need to return an array matching the interface. For instance you can make an array like:

```js
let stats: SubmissionAverageStatistics = [];
```

and populate with push,

```js
stats.push({ id: 1, plainAverage: 0.5 });
```

But how you make the array is up to you.

2021-01-23 21:17 UTC, shivanmodha commented
@sahej172002 what is the status of this one? Can we merge or withdraw?

2021-02-10 17:16 UTC, closed without merging